apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m0k25ro4h-go 
  janus-idp.io/tekton: m0k25ro4h-go
  backstage.io/kubernetes-id: m0k25ro4h-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m0k25ro4h-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml